export enum ENUM_AUTH_STATUS_CODE_ERROR {
  AUTH_JWT_ACCESS_TOKEN_ERROR = 5000,
  AUTH_JWT_ACCESS_TOKEN_EXPIRED = 5001,
  AUTH_JWT_ACCESS_TOKEN_UNAUTHORIZED = 5002,
  AUTH_JWT_ACCESS_TOKEN_INACTIVE = 5003,
  AUTH_JWT_PAYLOAD_ENCRYPTION = 5004,
  AUTH_JWT_REFRESH_TOKEN_ERROR = 5005,
  AUTH_GOOGLE_SSO_ERROR = 5006,
  AUTH_GOOGLE_SSO_MISSING_TOKEN_ERROR = 5007,
  AUTH_GOOGLE_SSO_INVALID_DOMAIN_ERROR = 5008,
  AUTH_INVALID_PARAMS_VALIDATION = 5009,
  AUTH_ERROR_SEND_EMAIL = 5010,
  AUTH_ERROR_CREATING_ACCOUNT = 50011,
  AUTH_INVALID_TOKEN = 5012,
  AUTH_INVALID_PARAMS_LOGIN_LENGTH = 5013,
}

export enum ENUM_USER_STATUS_CODE_ERROR {
  USER_NOT_FOUND = 5300,
  USER_NOT_VERIFIED = 5301,
  USER_INACTIVE = 5302,
  USER_ALREADY_VERIFIED = 5303,
}
